import { useNavigate } from 'react-router-dom';
import './quiz-hub.styles.scss';
import { FaRobot, FaUserCog } from 'react-icons/fa';
import { useEffect, useState } from 'react';
import { useUserAuthContext } from '../../contexts/user-auth-context.context';

const QuizHub = () => {
    const navigate = useNavigate();
    const { user } = useUserAuthContext();
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        // Ensure the user is authenticated before proceeding
        if (user) {
            setLoading(false);
        }
    }, [user]);

    const handleNavigateToAiQuiz = () => {
        navigate('/ai-quiz');
    };

    const handleNavigateToAdminQuiz = () => {
        navigate('/create-quiz');
    };

    if (loading) {
        return <div className="quiz-hub-container">Loading...</div>;
    }

    return (
        <div className="quiz-hub-container">
            <h1>Select Quiz Type</h1>
            <div className="quiz-options">
                <div className="quiz-option" onClick={handleNavigateToAiQuiz}>
                    <FaRobot className="quiz-icon" />
                    <h2>AI Generated Quiz</h2>
                    <p>Take a quiz generated by artificial intelligence</p>
                </div>
                <div className="quiz-option" onClick={handleNavigateToAdminQuiz}>
                    <FaUserCog className="quiz-icon" />
                    <h2>Admin Quiz</h2>
                    <p>Take a quiz created by administrators</p>
                </div>
            </div>
        </div>
    );
};

export default QuizHub; 